### PR TITLE
Fix project status link

### LINKED ISSUE #206: Single item in project status page are not showing as number.
In the project status lines the cell where only one sample appears show the sample name where they should show a 1 with a box and a link.

### PR DESCRIPTION
**Pull request by tcezard**
This PR fixes the link in project status page single sample do not appear as numbers.
Fixes #206 

This PR only affect the display of a link so it is very low risk.
This will bypass validation

### CODE REVIEW

File: reporting_app/static/column_formatter.js [hunk 1]
```diff
@@ -77,8 +77,8 @@ function string_formatter(cell_data, fmt, row){
 
     }
 
-    // if the list is longer than 1, then it should be rendered as a dropdown
-    if (formatted_data.length > 1) {
+    // if the list is longer than 1 or if it has special formatting, then it should be rendered as a dropdown
+    if (formatted_data.length > 1 || fmt['link_format_function']) {
```
Comment (lukbut) [inline reporting_app/static/column_formatter.js]: The "special formatting" refers to the the function which displays the length of the array and not the contents of it, in designated places.
